export default {
    en: {
        full_name: {
            name: 'Artem',
            surname: 'Tishchenko',
            linked: '@:full_name.name @:full_name.surname'
        },
        about_me: {
            about: 'About',
            me: 'me',
            linked: '@:about_me.about @:about_me.me'
        },
        my_info: "Let me tell you a few things....",
        welcome: "Welcome",
        sphere: "Vue.js, Laravel, PHP, Nuxt.js, Back-end, Front-end development",
        about: "About",
        about_work: "Development of Web-applications with Vue.js, Nuxt.js, Laravel frameworks. I work with MYSQL, PHP, Node.js. Develop own CMS, use technologies like CSS, JavaScript, HTML markup language.",
        quote: "To make a reasonable choice we must first of all know what is non-essential",
        quote_author: "Immanuel Kant",
        information: "Information",
        city_country: "City, country",
        city_country_name: "Kyiv, Ukraine",
        age: "Age",
        languages: "Languages",
        langs: "Russian, Ukrainian, English",
        technologies: "Technologies",
        no_inf: "No data",
        experience: "Experience",
        education: "Education",
        projects: "Projects",
        my_projects: {
            my: 'My',
            projects: '@.lower:projects',
        },
        projects_det: "Completed projects either functioning or ready for implementation",
        all: "All",
        blog: "Blog",
        blog_info: "Check out some of my posts....",
        my: 'My',
        notFound: "OOPS! Not found",
        notFoundMsg: "We are sorry, but the requested page does not exist",
        return: "Return to the main page",
        goto: "Go to the section",
        read_more: "Read more",
        load_more: "Load more",
        quest_com: "QUESTIONS OR PROPOSALS?",
        contacts: "GET IN TOUCH",
        contact: "Contacts",
        address: "Address",
        contact_me: "Contact me",
        name: "Your name",
        email: "Your Email",
        message: "Your message",
        cancel: "Cancel",
        send: "Send",
        site_name: "A. Tishchenko\'s personal website",
        login: "Login",
        clear: "Clear Form",
        home: "Home",
        register: "Sign up",
        logOut: "Logout",
        guest: "Guest",
        categories: "Categories",
        category: "Category",
        recent_entries: "Recent entries",
        recent_post: "Recent posts",
        search: "Search",
        author: "Author",
        source: "Source",
        tags: "Tags",
        tag: "Tag",
        comment: "Your comment",
        comments: "{n} comment | {n} comments",
        leave_com: "Leave a comment",
        post: "Post",
        hide: "Hide",
        password: "Password",
        password_more: "Password again",
        forgot: "Forgot Your Password?",
        resetPas: "Password reset",
        close: "Close",
        ch_avatar: "Change avatar",
        ch_file: "Choose file",
        cur_avatar: "Your current avatar",
        choose_avatar: "Choose your avatar (80x80)",
        reply: "Reply",
        from: "from",
        save: "Save",
        upload: "Upload",
        loading: "Processing...",
        not_found: "Sorry, no results",
        found: "Posts found",
        voted: "Thank you. Your vote has been counted.",
        on_query: "on request",
        email_sent: "The data has been successfully sent to your Email",
        comment_added: "Your comment has been successfully added",
        comment_removed: "Comment has been successfully deleted",
        msg_sent: "Your message has been successfully sent",
        error_file: "Invalid file type or size exceeded",
        error_msg: "Your message content is less than 10 or more than 2000 characters",
        error_auth: 'Error! You are not authorized!',
        error_email: 'Incorrect email address entered',
        error_query: 'Enter your query in the search bar',
        error_text: "Enter the text, or format it without unnecessary line breaks",
        error_length: "Your comment content is more than 8000 characters",
        error_pass_length: "Password must not be less than 6 characters",
        error_pass_match: "The passwords entered do not match.",
        error_email_exists: "Entered Email address already exists",
        error_no_user: "There is no user with such data.",
        error_login: "Invalid username. Special characters are not allowed in the username, or the length is less than 3 characters",
        error_try_later: "Something went wrong ... Please try again later",
    },
    ua: {
        full_name: {
            name: 'Артем',
            surname: 'Тищенко',
            linked: '@:full_name.name @:full_name.surname'
        },
        about_me: {
            about: 'Про',
            me: 'мене',
            linked: '@:about_me.about @:about_me.me'
        },
        my_info: "Кілька слів про себе...",
        welcome: "Ласкаво просимо",
        sphere: "Vue.js, Laravel, PHP, Nuxt.js, Back-end, Front-end розробка",
        about: "Про мене",
        about_work: "Займаюся розробкою Web-додатків за допомогою фреймворків Vue.js, Nuxt.js, Laravel. Працюю з MYSQL, PHP, Node.js. Створюю власні CMS. Використовую технології CSS, JavaScript, мову розмітки HTML.",
        quote: "Щоб зробити розумний вибір, треба перш за все знати, без чого можна обійтися",
        quote_author: "Іммануїл Кант",
        information: "Інформація",
        city_country: "Місто, країна",
        city_country_name: "Київ, Україна",
        age: "Вік",
        languages: "Мови",
        langs: "Російська, Українська, English",
        technologies: "Технології",
        no_inf: "Немає інформації",
        experience: "Досвід роботи",
        education: "Освіта",
        projects: "Проекти",
        my_projects: {
            my: 'Мої',
            projects: '@.lower:projects',
        },
        projects_det: "Реалізовані проекти, або функціонують, або готові до роботи",
        all: "Усе",
        blog: "Блог ",
        blog_info: "Мої публікації...",
        my: 'Мій',
        goto: "Перейти в розділ",
        read_more: "Читати далі",
        load_more: "Завантажити ще",
        quest_com: "ПИТАННЯ ЧИ ПРОПОЗИЦІЇ?",
        //contacts: "ЗВ\"ЯЗАТИСЯ,
        contact: "Контакти",
        address: "Адреса",
        contact_me: "Зв\'язатися зі мною",
        name: "Ваше ім\'я",
        email: "Ваш Email",
        message: "Ваше повідомлення",
        cancel: "Скасувати",
        send: "Надіслати",
        notFound: "OOPS! Не знайдено",
        notFoundMsg: "На жаль, запитувана сторінка не існує",
        return: "Повернутися на головну сторінку",
        site_name: "Персональний сайт А. Тищенко",
        login: "Увійти",
        clear: "Очистити форму",
        home: "Головна",
        register: "Реєстрація",
        logOut: "Вийти",
        guest: "Гість",
        categories: "Категорії",
        category: "Категорія",
        recent_entries: "Свіжі записи",
        recent_post: "Свіжі пости",
        search: "Пошук",
        author: "Автор",
        source: "Джерело",
        tags: "Теги",
        tag: "Тег",
        comment: "Ваш коментар",
        comments: "0 коментарів | {n} коментар | {n} коментаря | {n} коментарів",
        leave_com: "Залишити коментар",
        post: "Пост",
        hide: "Згорнути",
        password: "Пароль",
        password_more: "Пароль ще раз",
        forgot: "Забули свій пароль?",
        resetPas: "Відновлення паролю",
        close: "Закрити",
        ch_avatar: "Змінити аватар",
        ch_file: "Виберіть файл",
        cur_avatar: "Ваш поточний аватар",
        choose_avatar: "Виберіть ваш аватар (80x80)",
        reply: "Відповісти",
        from: "від",
        remove_ans: "Видалити відповідь",
        save: "Зберігти",
        upload: "Завантажити",
        loading: "Відправка...",
        not_found: "На жаль, нічого не знайдено",
        found: "Знайдено постів",
        voted: "Дякуємо. Ваш голос враховано.",
        on_query: "на запит",
        email_sent: "Дані успішно надіслано на Ваш Email",
        comment_added: "Ваш коментар успішно додано",
        comment_removed: "Коментар успішно видалено",
        msg_sent: "Ваше повідомлення успішно надіслано",
        error_file: "Неправильний тип або розмір файлу перевищено",
        error_msg: "Вміст повідомлення менше 10 або більше 2000 знаків",
        error_auth: 'Помилка! Ви не авторизовані!',
        error_email: 'Введено некоректну Email адресу',
        error_query: 'Введіть ваш запит в строку пошуку',
        error_text: "Введіть текст, або відформатуйте його без зайвих переносів строк",
        error_length: "Вміст Вашого коментаря перевищує 8000 знаків",
        error_pass_length: "Пароль не повинен бути меншим за 6 символів",
        error_pass_match: "Введені паролі не збігаються.",
        error_email_exists: "Така Email адреса вже існує",
        error_no_user: "Користувача з такими даними не існує",
        error_login: "Некоректне ім'я користувача. Спеціальні символи в імені користувача заборонені, або довжина менше 3 символів",
        error_try_later: "Щось пішло не так... Спробуйте пізніше",
    },
    ru: {
        full_name: {
            name: 'Артем',
            surname: 'Тищенко',
            linked: '@:full_name.name @:full_name.surname'
        },
        about_me: {
            about: 'Обо',
            me: 'мне',
            linked: '@:about_me.about @:about_me.me'
        },
        my_info: "Немного о себе...",
        welcome: "Добро пожаловать",
        sphere: "Vue.js, Laravel, PHP, Nuxt.js, Back-end, Front-end разработка",
        about: "Обо мне",
        about_work: "Занимаюсь разработкой Web-приложений с помощью фреймворков Vue.js, Nuxt.js, Laravel. Работаю с MYSQL, PHP, Node.js. Создаю собственные CMS. Использую CSS, JavaScript, язык разметки HTML.",
        quote: "Чтобы сделать разумный выбор, надо прежде всего знать, без чего можно обойтись",
        quote_author: "Иммануил Кант",
        information: "Информация",
        city_country: "Город, страна",
        city_country_name: "Киев, Украина",
        age: "Возраст",
        languages: "Языки",
        langs: "Русский, Українська, English",
        technologies: "Технологии",
        no_inf: "Нет информации",
        experience: "Опыт работы",
        education: "Образование",
        projects: "Проекты",
        my_projects: {
            my: 'Мои',
            projects: '@.lower:projects',
        },
        projects_det: "Завершенные проекты, либо функционирующие, либо готовые к работе",
        all: "Все",
        blog: "Блог",
        blog_info: "Мои публикации...",
        my: 'Мой',
        notFound: "OOPS! Не найдено.",
        notFoundMsg: "Сожалеем, но запрашиваемой страницы не существует",
        return: "Вернуться на главную страницу",
        goto: "Перейти в раздел",
        read_more: "Читать далее",
        load_more: "Загрузить еще",
        contacts: "СВЯЗАТЬСЯ",
        contact: "Контакты",
        quest_com: "ВОПРОСЫ ИЛИ ПРЕДЛОЖЕНИЯ?",
        address: "Адрес",
        contact_me: "Связаться со мной",
        name: "Ваше имя",
        email: "Ваш Email",
        message: "Ваше сообщение",
        cancel: "Отменить",
        send: "Отправить",
        site_name: "Персональный сайт А. Тищенко",
        login: "Войти",
        clear: "Очистить форму",
        home: "Главная",
        register: "Регистрация",
        logOut: "Выйти",
        guest: "Гoсть",
        categories: "Категории",
        category: "Категория",
        recent_entries: "Свежие записи",
        recent_post: "Недавние посты",
        search: "Поиск",
        author: "Автор",
        source: "Источник",
        tags: "Теги",
        tag: "Тег",
        comment: "Ваш комментарий",
        comments: "0 комментариев | {n} комментарий | {n} комментария | {n} комментариев",
        post: "Пост",
        leave_com: "Оставить комментарий",
        hide: "Свернуть",
        password: "Пароль",
        password_more: "Пароль еще раз",
        forgot: "Забыли свой пароль?",
        resetPas: "Сбросить пароль",
        close: "Закрыть",
        ch_avatar: "Сменить аватар",
        ch_file: "Выберите файл",
        cur_avatar: "Ваш текущий аватар",
        choose_avatar: "Выберите ваш аватар (80x80)",
        reply: "Ответить",
        from: "от",
        remove_ans: "Удалить ответ",
        save: "Сохранить",
        upload: "Загрузить",
        loading: "Отправка...",
        not_found: "К сожалению, ничего не найдено",
        found: "Найдено постов",
        voted: "Благодарим. Ваш голос учтен.",
        on_query: "по запросу",
        email_sent: "Данные успешно отправлены на Ваш Email",
        comment_added: "Ваш комментарий успешно добавлен",
        comment_removed: "Комментарий успешно удален",
        msg_sent: "Ваше сообщение успешно отправлено",
        error_file: "Неверный тип или размер файла превышен",
        error_msg: "Содержимое Вашего сообщения менее 10 или более 2000 знаков",
        error_auth: 'Ошибка! Вы не авторизованы',
        error_email: 'Введен некорректный Email адрес',
        error_query: 'Введите ваш запрос в строку поиска',
        error_text: "Введите текст, либо отформатируйте его без лишних переносов строк",
        error_length: "Содержимое Вашего комментария больше 8000 знаков",
        error_pass_length: "Пароль не должен быть менее 6 символов",
        error_pass_match: "Введенные пароли не совпадают.",
        error_email_exists: "Такой Email адрес уже существует",
        error_no_user: "Пользователя с такими данными не существует",
        error_login: "Некорректное имя пользователя. Специальные символы в имени пользователя запрещены, либо длина менее 3 символов",
        error_try_later: "Что-то пошло не так... Попробуйте позже",


    }
}
